name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      message:
        description: "Message to trigger hello"
        required: false
        default: ""

jobs:
  integrate-discord-fire:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Say hello when message is こんにちは！
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.message == 'こんにちは！' }}
        run: |
          echo "こんにちは！"
